# Generated by Django 4.2.17 on 2025-02-15 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_rename_price_product_unit_price_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer",
            name="store_custo_last_na_e6a359_idx",
        ),
        migrations.AlterModelTable(
            name="customer",
            table=None,
        ),
    ]
