# Generated by Django 4.2.17 on 2025-02-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_remove_customer_store_custo_last_na_e6a359_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="birthdate",
            new_name="birth_date",
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(),
        ),
    ]
