# Generated by Django 4.2.17 on 2025-02-15 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_rename_birthdate_customer_birth_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="last_updated",
            new_name="last_update",
        ),
    ]
